In [2]:
# Khai báo thư viện
import pandas as pd
import numpy as np
print('Khai báo thư viện thành công')

Khai báo thư viện thành công

In [3]:
# Nhập dữ liệu
data = pd.read_csv('C:\\Users\\hungu\\Jupyter baitap\\DATA\\DA - Datasets\\FoodPrice_in_Turkey.csv',
                   header=0, encoding = "ISO-8859-1")
print('*'*20, "Nhập dữ liệu thành công", '*'*20)
display(data)
# data2 = pd.read_csv('FoodPrice_in_Turkey.csv', header = 0, encoding = 'utf-8')
# display(data2)

******************** Nhập dữ liệu thành công ********************

,Place,ProductId,ProductName,UmId,UmName,Month,Year,Price
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

In [11]:
data.to_csv('second_time_FoodPrice.csv') #Khuyến cáo nên lưu ra file csv

In [5]:
data.info() #.info() method, hàm
# data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7381 entries, 0 to 7380
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Place        7381 non-null   object
 1   ProductId    7381 non-null   int64
 2   ProductName  7381 non-null   object
 3   UmId         7381 non-null   int64
 4   UmName       7381 non-null   object
 5   Month        7381 non-null   int64
 6   Year         7381 non-null   int64
 7   Price        7381 non-null   float64
dtypes: float64(1), int64(4), object(3)
memory usage: 461.4+ KB

In [6]:
#Xác định số dòng và số cột của dữ liệu
print(data.shape) # shape là property, tính chất, thuộc tính
#Số cột
print(data.shape[0])
#Số hàng
print(data.shape[1])

(7381, 8)
7381
8

In [7]:
# Xác định tên các cột
data.columns

Index(['Place', 'ProductId', 'ProductName', 'UmId', 'UmName', 'Month', 'Year',
       'Price'],
      dtype='object')

## Đổi tên cột

In [30]:
# Việt hóa tên các cột
# Đổi tên chỉ 1 cột xác định
# data.rename(columns = {'Place':'Địa điểm'}, inplace=True)

# Đổi tên chỉ 1 vài cột xác định
# data.rename(columns = {'ProductId':'Mã sản phẩm', 'ProductName':'Tên sản phẩm'}, inplace=True)
# data.rename(columns = {'UmId':'Số lượng', 'UmName':'Tên đơn vị'}, inplace=False) #Bảng data không thay đổi

# Đổi tên toàn bộ các cột (Yêu cầu liệt kê đầy đủ tên cột mới và theo đúng thứ tự)
data.columns = ['Địa điểm', 'Mã SP', 'Tên SP', 'Đơn vị', 'Tên đơn vị', 'Tháng', 'Năm', 'Giá'] #Phải đủ số lượng tên các cột

data

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Giá
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

## Thêm cột vào bảng đã có

In [31]:
# Thêm cột mới vào sau cuối
data['tên cột mới'] = np.NaN
data

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Giá,tên cột mới
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920,NaN
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786,NaN
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865,NaN
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337,NaN
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099,NaN
...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040,NaN
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176,NaN
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347,NaN
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985,NaN
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071,NaN

In [32]:
# Chèn thêm cột 'Chiết khấu' vào sau cột 'Giá'
data.insert(8,'Chiết khấu (%)', 20)
display(data)
# data.info()

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Giá,Chiết khấu (%),tên cột mới
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920,20,NaN
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786,20,NaN
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865,20,NaN
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337,20,NaN
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099,20,NaN
...,...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040,20,NaN
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176,20,NaN
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347,20,NaN
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985,20,NaN
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071,20,NaN

In [33]:
# Thêm 1 cột tên là "số lượng" nằm trước cột Giá, giá trị toàn bộ là 50
data.insert(7,'Số lượng',50)
data

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tên cột mới
0,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,NaN
1,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,NaN
2,National Average,52,Rice - Retail,5,KG,11,2013,50,4.7865,20,NaN
3,National Average,52,Rice - Retail,5,KG,12,2013,50,5.1337,20,NaN
4,National Average,52,Rice - Retail,5,KG,1,2014,50,5.5099,20,NaN
...,...,...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,50,47.9040,20,NaN
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,NaN
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,NaN
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,NaN
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,NaN

In [34]:
# Đổi tên "Tên cột mới" thành "Tổng" và có giá trị là giá*số lượng*(100%-chiết khấu)
# gợi ý: data['A'] = data[B]*C*(100-D)/100
data.rename(columns = {'tên cột mới':'tổng'}, inplace=True)
data['tổng'] = data['Giá'] * data['Số lượng'] * (100-data['Chiết khấu (%)'])/100
data

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
0,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
1,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
2,National Average,52,Rice - Retail,5,KG,11,2013,50,4.7865,20,191.460
3,National Average,52,Rice - Retail,5,KG,12,2013,50,5.1337,20,205.348
4,National Average,52,Rice - Retail,5,KG,1,2014,50,5.5099,20,220.396
...,...,...,...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,50,47.9040,20,1916.160
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284

In [13]:
data.shape[0]

7381

## Thêm 1 dòng mới vào cuối bảng
### df.loc[cs]=[....]
df.loc[df.shape[0]] = [....]

In [14]:
# Sai lầm
# data.loc[data.shape[0]]= ['Sài Gòn','3000','Dưa hấu','5','KG','10','6','2022','50.000','0','NaN']
# Chuẩn
data.loc[data.shape[0]]= ['Sài Gòn',3000,'Dưa hấu',5,'KG',10, 2022, 50,50.000,10,np.NaN]
display (data)
# data.info()

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
0,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
1,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
2,National Average,52,Rice - Retail,5,KG,11,2013,50,4.7865,20,191.460
3,National Average,52,Rice - Retail,5,KG,12,2013,50,5.1337,20,205.348
4,National Average,52,Rice - Retail,5,KG,1,2014,50,5.5099,20,220.396
...,...,...,...,...,...,...,...,...,...,...,...
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284
7381,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10,NaN

### Thêm 1 dòng mới vào đầu bảng

In [15]:
# Thêm 1 dòng mới vào đầu bảng
data.loc[-1]= ['Hà Nội',3001,'Cốm làng Vòng',5,'KG',10,2022,20, 50.000,30,np.NaN]
# Update index của bảng
data.index = data.index + 1
# Sắp xếp lại bảng
data = data.sort_index()
display(data)
# data.info()

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000,30,NaN
1,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
2,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
3,National Average,52,Rice - Retail,5,KG,11,2013,50,4.7865,20,191.460
4,National Average,52,Rice - Retail,5,KG,12,2013,50,5.1337,20,205.348
...,...,...,...,...,...,...,...,...,...,...,...
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284
7382,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10,NaN

### Thêm 1 dòng mới vào vị trí bất kỳ

In [16]:
#Cách 1: Swap giá trị các dòng
data.loc[-1] = data.loc[0]
data.loc[0] = ['Đà Nẵng',3002,'Mỳ Quảng',5,'Tô',10,2022,20, 100.000,10,np.NaN]
data.index = data.index +1
data = data.sort_index()

In [17]:
# Cách 2: Chèn thêm ở vị trí trung gian
# Chèn thêm dòng ở vị trí bất kỳ, ví dụ 0.5
data.loc[0.5]= ['Đà Nẫng',3002,'Mì quảng',5,'tô',10,9,2022,100.000,20,np.NaN]

#Sắp xếp lại các hàng theo đúng thứ tự từ nhỏ tới lớn và theo số tự nhiên
data = data.sort_index().reset_index(drop=True)

display(data)

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000,30,NaN
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000,20,NaN
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000,10,NaN
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
...,...,...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10,NaN

## Xóa cột

## Xóa cột sử dụng lệnh del
### del df['Tên cột cần xóa']

In [18]:
# Xóa cột sử dụng del
data2 = data
print('Data2 sau khi tạo')
display(data2)
# Xóa cột 'cột mới' (xóa ngay trên bảng gốc) -> Nguy hiểm, hạn chế dùng
del data2['tổng']
print('Data2 sau khi xóa')
display(data2)
print('Data sau khi xóa')
display(data)

Data2 sau khi tạo

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000,30,NaN
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000,20,NaN
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000,10,NaN
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
...,...,...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10,NaN

Data2 sau khi xóa

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%)
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000,30
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000,20
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000,10
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20
...,...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10

Data sau khi xóa

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%)
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000,30
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000,20
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000,10
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20
...,...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10

## Xóa cột sử dụng hàm pop()
### df.pop('Tên cột cần xóa')

In [19]:
# Xóa cột sử dụng pop()
data3 = data
print('Data3 sau khi tạo')
display(data3)
# Xóa cột 'cột mới' (xóa ngay trên bảng gốc) -> hạn chế dùng
data4 = data3.pop('Chiết khấu (%)') #-> kết quả là cột cần xóa
print('Data3 sau khi xóa')
display(data3)
print('Data sau khi xóa')
display(data)
print('Data4')
display(data4)

Data3 sau khi tạo

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%)
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000,30
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000,20
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000,10
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20
...,...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10

Data3 sau khi xóa

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786
...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000

Data sau khi xóa

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786
...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000

Data4

0       30
1       20
2       10
3       20
4       20
        ..
7380    20
7381    20
7382    20
7383    20
7384    10
Name: Chiết khấu (%), Length: 7385, dtype: int64

## Xóa cột sử dụng hàm drop()
### df.drop('Tên cột cần xóa’, axis=1, inplace=True/False)
axis = 1 nghĩa là xóa cột
inplace = True -> xóa cả dữ liệu gốc = del, pop()
inplace = False -> dữ lại nguyên vẹn dữ liệu gốc (mặc định)

In [20]:
# Xóa cột sử dụng drop()
data4 = data
print('Data4')
display(data4)
# Xóa cột 'cột mới' (không xóa trực tiếp trên bảng gốc) -> nên dùng
data5 = data4.drop('Số lượng', axis=1, inplace=False)  #-> lấy kết quả trả về
# data5 = data4.drop('Số lượng', axis=1, inplace=True)  #-> không trả về kết quả mà cột bị xóa trực tiếp trên bảng gốc
print('Data4 sau khi xóa')
display(data4)
print('Data5')
display(data5)
print('Data gốc')
display(data)

Data4

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786
...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000

Data4 sau khi xóa

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786
...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000

Data5

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Giá
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,50.0000
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,100.0000
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,100.0000
3,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
4,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50.0000

Data gốc

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000
2,Đà Nẵng,3002,Mỳ Quảng,5,Tô,10,2022,20,100.0000
3,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920
4,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786
...,...,...,...,...,...,...,...,...,...
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985
7383,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071
7384,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000

## Xóa nhiều cột sử dụng hàm drop()
### df.drop(['Tên cột cần xóa1',…, 'Tên cột cần xóa n'], axis=1, inplace=True/False)

In [23]:
# Xóa cột 'cột mới' và cột 'số lượng'
data6 = data.drop(['Chiết khấu (%)', 'Số lượng'], axis=1)
print('Data6')
display(data6)
print('Data gốc')
display(data)

KeyError: "['Chiết khấu (%)', 'Số lượng'] not found in axis"

## Xóa dòng sử dụng hàm drop()
### df.drop(cs, axis=0, inplace=True/False)
axis = 0 -> xóa dòng
cs là index của dòng đấy

In [ ]:
#Xóa dòng cuối cùng
data6 = data.drop(data.shape[0]-1, axis=0)
print("Data6")
display(data6)

In [103]:
# Xóa dòng đầu tiên của bảng
data7 = data.drop(0, axis=0) #-> xóa đi và không reset lại index
display(data)
display(data7)
# data7.info()

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000,30,NaN
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000,20,NaN
2,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
3,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
4,National Average,52,Rice - Retail,5,KG,11,2013,50,4.7865,20,191.460
...,...,...,...,...,...,...,...,...,...,...,...
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284
7383,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10,NaN

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000,20,NaN
2,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
3,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
4,National Average,52,Rice - Retail,5,KG,11,2013,50,4.7865,20,191.460
5,National Average,52,Rice - Retail,5,KG,12,2013,50,5.1337,20,205.348
...,...,...,...,...,...,...,...,...,...,...,...
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284
7383,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10,NaN

## Xóa nhiều dòng sử dụng hàm drop()
### df.drop([cs1,…,csn], axis=0, inplace=True)

In [95]:
data

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
0,Hà Nội,3001,Cốm làng Vòng,5,KG,10,2022,20,50.0000,30,NaN
1,Đà Nẫng,3002,Mì quảng,5,tô,10,9,2022,100.0000,20,NaN
2,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
3,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
4,National Average,52,Rice - Retail,5,KG,11,2013,50,4.7865,20,191.460
...,...,...,...,...,...,...,...,...,...,...,...
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284
7383,Sài Gòn,3000,Dưa hấu,5,KG,10,2022,50,50.0000,10,NaN

In [96]:
# Xóa dòng thứ Đà Nẵng, Hà Nội và Sài Gòn
data8 = data.drop([0,1,7383], axis=0)
data8

,Địa điểm,Mã SP,Tên SP,Đơn vị,Tên đơn vị,Tháng,Năm,Số lượng,Giá,Chiết khấu (%),tổng
2,National Average,52,Rice - Retail,5,KG,5,2013,50,4.4920,20,179.680
3,National Average,52,Rice - Retail,5,KG,6,2013,50,4.5786,20,183.144
4,National Average,52,Rice - Retail,5,KG,11,2013,50,4.7865,20,191.460
5,National Average,52,Rice - Retail,5,KG,12,2013,50,5.1337,20,205.348
6,National Average,52,Rice - Retail,5,KG,1,2014,50,5.5099,20,220.396
...,...,...,...,...,...,...,...,...,...,...,...
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,50,47.9040,20,1916.160
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,50,49.1176,20,1964.704
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50,50.8347,20,2033.388
7381,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,50,51.7985,20,2071.940
7382,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,50,51.6071,20,2064.284

In [4]:
data.pivot_table(values='Price',index='ProductName',columns='Year',aggfunc='mean')

Year,2013,2014,2015,2016,2017,2018,2019
ProductName,,,,,,,
Apples (red) - Retail,2.080950,2.410118,2.401417,2.428333,2.560000,NaN,NaN
Apples - Retail,NaN,NaN,NaN,NaN,3.334175,3.923417,4.259810
Bananas - Retail,4.002225,4.962827,5.368833,5.914167,7.313738,8.701475,10.879371
Beans (white) - Retail,6.932800,9.484309,7.288333,6.949167,9.217700,9.242844,11.658690
Bread (common) - Retail,2.853000,3.069491,2.982917,3.373333,4.178841,4.740619,5.513271
Bread (pita) - Retail,NaN,NaN,2.311429,2.440000,2.480000,NaN,NaN
Bulgur - Retail,2.405025,2.593791,2.680500,2.765833,3.293874,3.546027,4.369369
Cabbage - Retail,1.104800,1.073233,1.197000,1.375714,1.589495,1.751664,2.232738
Cauliflower - Retail,2.046950,2.129317,2.772800,2.655714,2.878481,3.237750,4.326537
Cheese - Retail,NaN,NaN,15.421429,15.490833,24.425554,27.905196,28.013267
Chickpeas - Retail,5.918450,5.815827,5.665250,7.765000,13.577754,12.243981,9.051525
Cocoa (powder) - Retail,37.795150,38.134264,36.657917,36.696667,43.299851,45.214012,48.160994
Coffee (instant) - Retail,39.954750,36.359891,29.626917,35.796667,45.395493,50.388579,42.705810
Coffee - Retail,30.890625,31.261200,34.499917,36.154167,42.082349,44.706650,47.646450
Cucumbers (greenhouse) - Retail,1.737400,1.936482,1.977083,2.298333,4.376667,NaN,NaN
Cucumbers - Retail,NaN,NaN,NaN,NaN,2.902958,3.180702,4.023225
Eggplants - Retail,NaN,NaN,1.917143,2.550000,3.543931,3.641333,5.018958
Eggs - Retail,0.310175,0.350036,0.352250,0.361667,0.480056,0.609846,0.549542
Electricity - Retail,NaN,NaN,NaN,NaN,0.411850,0.502633,0.600825
Fish (fresh) - Retail,13.461625,14.228209,14.089750,15.066667,20.882454,24.301085,29.341567
Fuel (gas) - Retail,NaN,NaN,63.548571,64.800000,77.366069,88.545933,92.551890
Fuel (petrol-gasoline) - Retail,NaN,NaN,4.590000,4.535000,5.291772,6.253287,15.211690
Garlic - Retail,8.143075,8.758027,10.943750,14.851667,14.835772,13.024994,25.999040
Groundnuts (shelled) - Retail,12.605350,12.779155,17.512000,17.527500,19.470874,21.036458,29.546023
Lentils - Retail,3.452275,4.467318,5.786250,6.957500,7.807254,6.684435,6.587621
Meat (chicken) - Retail,6.677175,7.224882,7.024250,7.434167,8.890931,9.954510,12.097452
Meat (mutton) - Retail,25.609925,26.065691,27.004750,31.058333,43.883523,51.335848,55.530354
Meat (veal) - Retail,25.021700,27.711155,33.118250,37.070833,41.791177,43.621363,46.047448
Milk (pasteurized) - Retail,2.379750,2.643636,2.817833,2.907500,3.168628,4.080617,4.448258
"Milk (powder, infant formula) - Retail",NaN,NaN,63.757143,70.695833,85.364697,123.919679,127.172654
Oil (olive) - Retail,10.615950,12.710382,21.570500,27.822500,29.237797,30.880817,28.087996
Oil (sunflower) - Retail,6.082575,6.159518,8.214250,7.721667,8.173803,9.042829,10.151044
Onions - Retail,1.064950,1.088882,1.375250,1.481667,1.276641,2.564400,3.108898
Oranges - Retail,3.792200,1.630714,1.712429,1.621250,2.852100,2.982422,4.339036
Pasta - Retail,2.370975,2.687491,2.944917,2.995833,3.160313,3.494312,4.314592
"Peas (green, dry) - Retail",2.385100,3.015000,3.166667,NaN,NaN,NaN,NaN
Potatoes - Retail,NaN,NaN,1.538571,1.094167,1.636687,2.442390,3.100167
Rice - Retail,4.747700,6.367855,6.426833,6.047500,7.164792,8.640444,9.384565
Salt - Retail,1.434225,1.462836,1.516083,1.666667,1.998374,2.232254,2.318398
Spinach - Retail,NaN,NaN,2.660000,2.292857,2.642886,2.802390,4.477733
Sugar - Retail,3.554150,3.783709,3.852667,4.175833,4.277897,4.655442,4.949027
Tea (green) - Retail,3.590825,3.897700,4.084667,4.460000,4.660000,NaN,NaN
Tea (herbal) - Retail,NaN,NaN,NaN,NaN,5.016853,5.838017,5.345148
Tea - Retail,14.152900,16.543309,19.870750,22.537500,27.112123,28.601408,28.860771
Tomatoes (paste) - Retail,NaN,NaN,6.771429,6.479167,5.839510,7.688948,10.898944
Tomatoes - Retail,1.833025,1.936864,1.927667,1.914167,3.012379,3.897779,4.399598
Transport (public) - Retail,NaN,NaN,NaN,NaN,2.569043,2.425712,2.436694
"Wage (non-qualified labour, non-agricultural) - Retail",NaN,NaN,33.100000,43.330000,46.800000,NaN,NaN
Water - Retail,NaN,NaN,NaN,NaN,5.052814,5.826585,5.190500
Wheat flour - Retail,2.255350,2.565082,2.672583,2.848333,3.132718,3.405498,3.685917
Yogurt - Retail,NaN,NaN,3.984286,3.935833,4.783010,5.804490,5.956696
Zucchini - Retail,NaN,NaN,NaN,NaN,3.477094,3.656315,4.288779

In [5]:
data.pivot_table(values='Price',index='ProductName',columns='Year',aggfunc ='max')

Year,2013,2014,2015,2016,2017,2018,2019
ProductName,,,,,,,
Apples (red) - Retail,2.3878,2.8952,2.980,2.83,2.8300,NaN,NaN
Apples - Retail,NaN,NaN,NaN,NaN,5.3033,5.1543,6.0925
Bananas - Retail,4.0779,5.7980,5.880,6.67,8.9246,11.5253,12.9400
Beans (white) - Retail,8.5757,10.2467,7.665,7.65,10.3193,12.4070,13.0975
Bread (common) - Retail,2.9149,3.2623,3.140,3.76,4.8107,5.6603,6.1942
Bread (pita) - Retail,NaN,NaN,2.360,2.56,2.4800,NaN,NaN
Bulgur - Retail,2.4369,2.6614,2.730,2.87,3.6822,4.4844,5.2611
Cabbage - Retail,1.1181,1.1632,1.318,1.50,2.2753,2.4855,3.2543
Cauliflower - Retail,2.3045,2.9470,3.232,3.98,4.7759,4.6490,5.9113
Cheese - Retail,NaN,NaN,15.620,18.73,30.1573,32.8791,35.5297
Chickpeas - Retail,6.1726,5.9180,6.240,10.61,15.5274,14.6566,10.4517
Cocoa (powder) - Retail,38.1419,38.7882,37.337,39.06,47.2439,53.7658,54.8237
Coffee (instant) - Retail,40.1146,39.7204,30.070,39.03,58.5085,61.3502,55.8566
Coffee - Retail,31.0164,31.6590,35.740,38.98,44.9789,54.9968,51.5928
Cucumbers (greenhouse) - Retail,2.3567,2.7623,3.119,3.30,4.5700,NaN,NaN
Cucumbers - Retail,NaN,NaN,NaN,NaN,5.6738,4.2470,7.1657
Eggplants - Retail,NaN,NaN,2.640,4.26,6.8744,5.7391,11.1584
Eggs - Retail,0.3635,0.3889,0.400,0.57,0.6107,0.8300,0.7891
Electricity - Retail,NaN,NaN,NaN,NaN,0.4120,0.5972,0.7102
Fish (fresh) - Retail,13.9392,15.6697,15.110,17.08,26.4764,30.5595,37.7223
Fuel (gas) - Retail,NaN,NaN,65.240,69.67,86.9783,97.2577,112.4568
Fuel (petrol-gasoline) - Retail,NaN,NaN,4.840,5.13,5.6260,6.9972,111.2686
Garlic - Retail,8.3617,9.5358,15.330,19.77,20.1185,18.9205,41.7712
Groundnuts (shelled) - Retail,12.7324,13.3945,19.430,18.10,21.6830,23.8909,36.0327
Lentils - Retail,3.6645,5.0000,6.240,7.19,8.6060,7.6654,7.8415
Meat (chicken) - Retail,7.3100,7.7342,7.530,7.93,10.5681,12.0229,15.6383
Meat (mutton) - Retail,25.7582,27.1764,28.240,34.12,50.5976,57.3508,59.3223
Meat (veal) - Retail,25.9683,30.3661,35.690,38.57,45.4883,48.3661,49.7239
Milk (pasteurized) - Retail,2.4882,2.8430,2.872,2.96,3.5807,4.7517,5.3813
"Milk (powder, infant formula) - Retail",NaN,NaN,65.540,76.96,93.9628,159.4458,150.0380
Oil (olive) - Retail,10.9123,13.3716,27.180,28.40,30.8409,34.7226,30.1293
Oil (sunflower) - Retail,6.2098,6.2600,22.740,7.88,8.8251,10.9393,11.2261
Onions - Retail,1.1584,1.1820,1.740,2.64,1.6489,4.6032,6.5986
Oranges - Retail,5.9520,2.3310,2.510,2.49,4.2013,3.8761,7.0085
Pasta - Retail,2.3976,2.8370,3.030,3.05,3.3305,4.0496,5.0748
"Peas (green, dry) - Retail",2.3882,3.5312,3.410,NaN,NaN,NaN,NaN
Potatoes - Retail,NaN,NaN,1.860,1.39,2.1628,3.8050,5.5475
Rice - Retail,5.1337,6.7240,6.755,6.39,8.4292,10.2796,10.4043
Salt - Retail,1.4716,1.4919,1.600,1.77,2.2083,2.9118,2.7772
Spinach - Retail,NaN,NaN,2.880,3.40,3.5793,3.8405,6.7115
Sugar - Retail,3.6451,4.0144,4.030,4.31,4.6351,5.0766,5.5038
Tea (green) - Retail,3.6888,4.0910,4.171,4.59,4.7200,NaN,NaN
Tea (herbal) - Retail,NaN,NaN,NaN,NaN,5.9503,6.9347,5.9599
Tea - Retail,14.3991,18.2830,21.420,23.83,30.8234,31.8628,35.4751
Tomatoes (paste) - Retail,NaN,NaN,6.810,6.70,6.2700,12.4038,11.5304
Tomatoes - Retail,2.0484,2.4550,2.750,3.08,4.5217,5.8000,7.3245
Transport (public) - Retail,NaN,NaN,NaN,NaN,2.9504,3.1529,3.6964
"Wage (non-qualified labour, non-agricultural) - Retail",NaN,NaN,33.350,43.33,46.8000,NaN,NaN
Water - Retail,NaN,NaN,NaN,NaN,6.3605,7.4418,6.0740
Wheat flour - Retail,2.3416,2.6550,2.750,2.93,3.4715,4.5670,4.2703
Yogurt - Retail,NaN,NaN,4.010,4.06,5.5461,6.9722,7.4009
Zucchini - Retail,NaN,NaN,NaN,NaN,7.0347,5.9041,7.3851

In [7]:
data.pivot_table(values='Price',index='ProductName',aggfunc ='max')

                                                       Price
ProductName
Apples (red) - Retail                                 2.9800
Apples - Retail                                       6.0925
Bananas - Retail                                     12.9400
Beans (white) - Retail                               13.0975
Bread (common) - Retail                               6.1942
Bread (pita) - Retail                                 2.5600
Bulgur - Retail                                       5.2611
Cabbage - Retail                                      3.2543
Cauliflower - Retail                                  5.9113
Cheese - Retail                                      35.5297
Chickpeas - Retail                                   15.5274
Cocoa (powder) - Retail                              54.8237
Coffee (instant) - Retail                            61.3502
Coffee - Retail                                      54.9968
Cucumbers (greenhouse) - Retail                       4.5700
Cucumbers - Retail                                    7.1657
Eggplants - Retail                                   11.1584
Eggs - Retail                                         0.8300
Electricity - Retail                                  0.7102
Fish (fresh) - Retail                                37.7223
Fuel (gas) - Retail                                 112.4568
Fuel (petrol-gasoline) - Retail                     111.2686
Garlic - Retail                                      41.7712
Groundnuts (shelled) - Retail                        36.0327
Lentils - Retail                                      8.6060
Meat (chicken) - Retail                              15.6383
Meat (mutton) - Retail                               59.3223
Meat (veal) - Retail                                 49.7239
Milk (pasteurized) - Retail                           5.3813
Milk (powder, infant formula) - Retail              159.4458
Oil (olive) - Retail                                 34.7226
Oil (sunflower) - Retail                             22.7400
Onions - Retail                                       6.5986
Oranges - Retail                                      7.0085
Pasta - Retail                                        5.0748
Peas (green, dry) - Retail                            3.5312
Potatoes - Retail                                     5.5475
Rice - Retail                                        10.4043
Salt - Retail                                         2.9118
Spinach - Retail                                      6.7115
Sugar - Retail                                        5.5038
Tea (green) - Retail                                  4.7200
Tea (herbal) - Retail                                 6.9347
Tea - Retail                                         35.4751
Tomatoes (paste) - Retail                            12.4038
Tomatoes - Retail                                     7.3245
Transport (public) - Retail                           3.6964
Wage (non-qualified labour, non-agricultural) -...   46.8000
Water - Retail                                        7.4418
Wheat flour - Retail                                  4.5670
Yogurt - Retail                                       7.4009
Zucchini - Retail                                     7.3851

In [9]:
data.pivot_table(values=['Price','Month'],columns='Place',index='ProductName',aggfunc ={'Price': np.sum,'Month': np.mean})

                                                       Month            \
Place                                                 Ankara  Istanbul
ProductName
Apples (red) - Retail                                    NaN       NaN
Apples - Retail                                     6.500000  6.500000
Bananas - Retail                                    6.500000  6.500000
Beans (white) - Retail                              6.500000  6.500000
Bread (common) - Retail                             6.500000  6.500000
Bread (pita) - Retail                                    NaN       NaN
Bulgur - Retail                                     6.500000  6.500000
Cabbage - Retail                                    6.421053  6.421053
Cauliflower - Retail                                6.294118  6.294118
Cheese - Retail                                     6.500000  6.500000
Chickpeas - Retail                                  6.500000  6.500000
Cocoa (powder) - Retail                             6.500000  6.500000
Coffee (instant) - Retail                           7.071429  7.071429
Coffee - Retail                                     6.500000  6.500000
Cucumbers (greenhouse) - Retail                          NaN       NaN
Cucumbers - Retail                                  6.500000  6.500000
Eggplants - Retail                                  6.500000  6.500000
Eggs - Retail                                       6.500000  6.500000
Electricity - Retail                                6.500000  6.500000
Fish (fresh) - Retail                               6.500000  6.500000
Fuel (gas) - Retail                                 6.500000  6.500000
Fuel (petrol-gasoline) - Retail                     6.500000  6.500000
Garlic - Retail                                     6.500000  6.500000
Groundnuts (shelled) - Retail                       6.500000  6.500000
Lentils - Retail                                    6.500000  6.500000
Meat (chicken) - Retail                             6.500000  6.500000
Meat (mutton) - Retail                              6.500000  6.500000
Meat (veal) - Retail                                6.500000  6.500000
Milk (pasteurized) - Retail                         6.500000  6.500000
Milk (powder, infant formula) - Retail              6.500000  6.500000
Oil (olive) - Retail                                6.500000  6.500000
Oil (sunflower) - Retail                            6.500000  6.500000
Onions - Retail                                     6.500000  6.500000
Oranges - Retail                                    5.846154  5.846154
Pasta - Retail                                      6.500000  6.500000
Peas (green, dry) - Retail                               NaN       NaN
Potatoes - Retail                                   6.500000  6.500000
Rice - Retail                                       6.500000  6.500000
Salt - Retail                                       6.500000  6.500000
Spinach - Retail                                    6.294118  6.294118
Sugar - Retail                                      6.500000  6.500000
Tea (green) - Retail                                     NaN       NaN
Tea (herbal) - Retail                               6.500000  6.500000
Tea - Retail                                        6.500000  6.500000
Tomatoes (paste) - Retail                           6.500000  6.500000
Tomatoes - Retail                                   6.500000  6.500000
Transport (public) - Retail                         6.428571  6.500000
Wage (non-qualified labour, non-agricultural) -...       NaN       NaN
Water - Retail                                      6.500000  6.500000
Wheat flour - Retail                                6.500000  6.500000
Yogurt - Retail                                     6.500000  6.500000
Zucchini - Retail                                   6.500000  6.500000

                                                                               \
Place                                                  Izmir National Average
ProductName
Apples (red) - Retail                                    NaN         6.428571
Apples - Retail                                     6.500000         6.500000
Bananas - Retail                                    6.500000         6.454545
Beans (white) - Retail                              6.500000         6.454545
Bread (common) - Retail                             6.500000         6.454545
Bread (pita) - Retail                                    NaN         6.681818
Bulgur - Retail                                     6.500000         6.454545
Cabbage - Retail                                    6.421053         6.194444
Cauliflower - Retail                                6.294118         6.117647
Cheese - Retail                                     6.500000         6.586957
Chickpeas - Retail                                  6.500000         6.454545
Cocoa (powder) - Retail                             6.500000         6.454545
Coffee (instant) - Retail                           7.071429         6.454545
Coffee - Retail                                     6.500000         6.454545
Cucumbers (greenhouse) - Retail                          NaN         6.428571
Cucumbers - Retail                                  6.500000         6.500000
Eggplants - Retail                                  6.500000         6.586957
Eggs - Retail                                       6.500000         6.454545
Electricity - Retail                                6.500000         6.500000
Fish (fresh) - Retail                               6.500000         6.454545
Fuel (gas) - Retail                                 6.500000         6.586957
Fuel (petrol-gasoline) - Retail                     6.500000         6.586957
Garlic - Retail                                     6.500000         6.454545
Groundnuts (shelled) - Retail                       6.500000         6.454545
Lentils - Retail                                    6.500000         6.454545
Meat (chicken) - Retail                             6.500000         6.454545
Meat (mutton) - Retail                              6.500000         6.454545
Meat (veal) - Retail                                6.500000         6.454545
Milk (pasteurized) - Retail                         6.500000         6.454545
Milk (powder, infant formula) - Retail              6.500000         6.586957
Oil (olive) - Retail                                6.500000         6.454545
Oil (sunflower) - Retail                            6.500000         6.454545
Onions - Retail                                     6.500000         6.454545
Oranges - Retail                                    5.846154         5.840909
Pasta - Retail                                      6.500000         6.454545
Peas (green, dry) - Retail                               NaN         5.285714
Potatoes - Retail                                   6.500000         6.586957
Rice - Retail                                       6.500000         6.454545
Salt - Retail                                       6.500000         6.454545
Spinach - Retail                                    6.294118         6.250000
Sugar - Retail                                      6.500000         6.454545
Tea (green) - Retail                                     NaN         6.428571
Tea (herbal) - Retail                               6.500000         6.500000
Tea - Retail                                        6.500000         6.454545
Tomatoes (paste) - Retail                           6.500000         6.586957
Tomatoes - Retail                                   6.500000         6.454545
Transport (public) - Retail                         6.500000         6.500000
Wage (non-qualified labour, non-agricultural) -...       NaN         6.681818
Water - Retail                                      6.500000         6.500000
Wheat flour - Retail                                6.500000         6.454545
Yogurt - Retail                                     6.500000         6.586957
Zucchini - Retail                                   6.500000         6.500000

                                                        Price             \
Place                                                  Ankara   Istanbul
ProductName
Apples (red) - Retail                                     NaN        NaN
Apples - Retail                                      133.6730   147.7027
Bananas - Retail                                     304.7437   327.6029
Beans (white) - Retail                               332.6128   383.5499
Bread (common) - Retail                              167.4157   184.6184
Bread (pita) - Retail                                     NaN        NaN
Bulgur - Retail                                      129.5859   143.0773
Cabbage - Retail                                      31.8945    38.3249
Cauliflower - Retail                                  56.4567    69.1003
Cheese - Retail                                      961.9613   980.0739
Chickpeas - Retail                                   378.5647   438.2447
Cocoa (powder) - Retail                             1613.8489  1700.9064
Coffee (instant) - Retail                           1045.5429  1424.2491
Coffee - Retail                                     1573.6823  1604.3165
Cucumbers (greenhouse) - Retail                           NaN        NaN
Cucumbers - Retail                                   117.3324   128.5635
Eggplants - Retail                                   136.3472   153.3957
Eggs - Retail                                         18.0299    20.8500
Electricity - Retail                                  18.1837    18.1837
Fish (fresh) - Retail                                887.1821  1035.5012
Fuel (gas) - Retail                                 3055.7316  3200.5098
Fuel (petrol-gasoline) - Retail                      319.4124   322.7623
Garlic - Retail                                      548.1320   716.8176
Groundnuts (shelled) - Retail                        796.0976   898.2896
Lentils - Retail                                     243.2624   262.8975
Meat (chicken) - Retail                              352.9688   385.8055
Meat (mutton) - Retail                              1785.0146  1909.8477
Meat (veal) - Retail                                1522.3885  1609.5090
Milk (pasteurized) - Retail                          138.4768   143.5290
Milk (powder, infant formula) - Retail              3867.4508  4009.7087
Oil (olive) - Retail                                1044.9484  1072.4479
Oil (sunflower) - Retail                             323.0173   344.1325
Onions - Retail                                       73.7092    88.4918
Oranges - Retail                                      87.4031    97.6397
Pasta - Retail                                       130.8555   134.9679
Peas (green, dry) - Retail                                NaN        NaN
Potatoes - Retail                                     81.1773    90.8639
Rice - Retail                                        280.8815   316.1799
Salt - Retail                                         74.0132    84.0101
Spinach - Retail                                      50.7829    62.5746
Sugar - Retail                                       160.7533   173.0889
Tea (green) - Retail                                      NaN        NaN
Tea (herbal) - Retail                                183.6941   198.3318
Tea - Retail                                         950.0084  1027.7726
Tomatoes (paste) - Retail                            277.9238   291.0017
Tomatoes - Retail                                    134.0984   143.4385
Transport (public) - Retail                           85.7563    72.3179
Wage (non-qualified labour, non-agricultural) -...        NaN        NaN
Water - Retail                                       212.7846   204.3195
Wheat flour - Retail                                 107.5198   131.2668
Yogurt - Retail                                      190.2318   203.0441
Zucchini - Retail                                    128.4446   152.0505


Place                                                   Izmir National Average
ProductName
Apples (red) - Retail                                     NaN         100.4721
Apples - Retail                                      137.8665          93.5830
Bananas - Retail                                     342.8845         455.8813
Beans (white) - Retail                               379.3065         570.2033
Bread (common) - Retail                              171.5711         253.0077
Bread (pita) - Retail                                     NaN          52.9000
Bulgur - Retail                                      135.1067         204.1380
Cabbage - Retail                                      36.6622          53.3941
Cauliflower - Retail                                  54.5321          98.2747
Cheese - Retail                                     1035.2488         953.2388
Chickpeas - Retail                                   458.0320         525.6862
Cocoa (powder) - Retail                             1637.9016        2668.9501
Coffee (instant) - Retail                           1559.8856        2464.6463
Coffee - Retail                                     1682.7990        2528.6473
Cucumbers (greenhouse) - Retail                           NaN          92.6859
Cucumbers - Retail                                   118.9467          85.4524
Eggplants - Retail                                   145.5896         162.5948
Eggs - Retail                                         21.2919          27.8591
Electricity - Retail                                  18.1837          13.2415
Fish (fresh) - Retail                                789.4628        1237.3507
Fuel (gas) - Retail                                 3068.0847        3608.0861
Fuel (petrol-gasoline) - Retail                      321.2965         359.7768
Garlic - Retail                                      693.2822         931.9725
Groundnuts (shelled) - Retail                        852.7035        1251.6986
Lentils - Retail                                     263.5486         387.7077
Meat (chicken) - Retail                              379.5504         566.5992
Meat (mutton) - Retail                              1851.8339        2380.2582
Meat (veal) - Retail                                1621.6671        2427.5727
Milk (pasteurized) - Retail                          141.4499         216.8098
Milk (powder, infant formula) - Retail              4306.6330        4492.5127
Oil (olive) - Retail                                1063.7668        1564.6080
Oil (sunflower) - Retail                             317.7816         538.4688
Onions - Retail                                       88.3118         122.1150
Oranges - Retail                                      87.0786         109.0408
Pasta - Retail                                       131.5066         211.0849
Peas (green, dry) - Retail                                NaN          20.3002
Potatoes - Retail                                     87.7596          93.9727
Rice - Retail                                        318.6902         467.6049
Salt - Retail                                         81.3386         117.0271
Spinach - Retail                                      56.8981          72.7884
Sugar - Retail                                       165.4068         280.7829
Tea (green) - Retail                                      NaN         173.7540
Tea (herbal) - Retail                                199.5347         135.8380
Tea - Retail                                        1093.0043        1492.2591
Tomatoes (paste) - Retail                            307.5030         368.6812
Tomatoes - Retail                                    134.9070         178.0526
Transport (public) - Retail                          110.4762          54.7616
Wage (non-qualified labour, non-agricultural) -...        NaN         892.0600
Water - Retail                                       180.0569         113.5604
Wheat flour - Retail                                 130.8998         196.3658
Yogurt - Retail                                      209.4428         223.4756
Zucchini - Retail                                    133.6774          92.3674